[package]
name = "web-scrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
reqwest = { version = "0.11.6", features = ["blocking", "json"] }
rayon = "1.10.0"
serde = "1.0.219"
serde_json = "1.0.140"
scraper = "0.23.1"
